apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  labels:
    name: springapp
  annotations:
spec:
  selector:
    matchLabels:
      name: springapp
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: springapp
    spec:
      containers:
      - name: springapp
        image: bsarathkumar42/myspringimage:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springapp
  name: springapp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: springapp
